export const CARE_TAKER = 'CARE_TAKER';
export const PET_OWNER = 'PET_OWNER';
export const ADMINISTRATOR = 'ADMINISTRATOR';
export const CARE_TAKER_FULL_TIMER = 'CARE_TAKER_FULL_TIMER';
export const CARE_TAKER_PART_TIMER = 'CARE_TAKER_PART_TIMER';
